export const Tools  =[
     {
    id: 1,
    image:'/tools/vscode.png',
    name: "Visual Studio Code",
   info: "Code Editor",
    dad: "100",
  },
  {
    id: 2,
 image:'/tools/reactjs.png',
    name: "React JS",
   info: "Framework",
    dad: "200",
  },
  {
    id: 3,
 image:'/tools/nextjs.png',
    name: "Next JS",
   info: "Framework",
    dad: "300",
  },
  {
    id: 4,
 image:'/tools/tailwind.png',
    name: "Tailwind CSS",
   info: "Framework",
    dad: "400",
  },
  {
    id: 5,
 image:'/tools/bootstrap.png',
    name: "Bootstrap",
   info: "Framework",
    dad: "500",
  },
  {
    id: 6,
    image:'/tools/js.png',
    name: "Javascript",
   info: "Language",
    dad: "600",
  },
  {
    id: 7,
     image:'/tools/django.png',
    name: "Django",
   info: "Javascript Runtime",
    dad: "700",
  },
  {
    id: 8,
 image:'/tools/github.png',
    name: "Github",
   info: "Repository",
    dad: "800",
  },
  {
    id: 9,
 image:'/tools/Ai.png',
    name: "Adobe Illustrator",
   info: "Design App",
    dad: "900",
  },
  {
    id: 10,
  image:'/tools/canva.png',
    name: "Canva",
   info: "Design App",
    dad: "1000",
  },
  {
    id: 11,
  image:'/tools/figma.png',
    name: "Figma",
   info: "Design App",
    dad: "1100",
  },
 

  {
    id: 14,
    name: "HTML",
     image:'/tools/html.png',
   info: "Language",
    dad: "1400",
  },
  {
    id: 15,
    name: "CSS",
     image:'/tools/css.png',
   info: "Language",
    dad: "1500",
  },

  {
    id: 17,
  image:'/tools/php.png',
    name: "PHP",
   info: "Language",
    dad: "1700",
  },
  {
    id: 18,
    image:'/tools/vite.png',
    name: "Vite",
   info: "Framework",
    dad: "1800",
  },
  {
    id: 19,
    image:'/tools/mysql.png',
    name: "MySql",
   info: "Framework",
    dad: "1900",
  },
]